version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: sunil
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sunil", "-d", "library"]
      interval: 10s
      retries: 5
      timeout: 5s

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://sunil:mypassword@postgres:5432/library
    ports:
      - "5000:5000"
    volumes:
      - .:/app
